apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databases.internal.example:kcp-sync-agent
rules:
  - apiGroups:
      - "database.example.crossplane.io"
    resources:
      - mysqldatabases
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: databases.internal.example:kcp-sync-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: databases.internal.example:kcp-sync-agent
subjects:
  - kind: ServiceAccount
    name: kcp-api-syncagent
    namespace: kcp-sync-agent
