apiVersion: syncagent.kcp.io/v1alpha1
kind: PublishedResource
metadata:
  name: databases.internal.example
spec:
  resource:
    kind: MySQLDatabase
    apiGroup: database.example.crossplane.io
    versions: [v1]
  related:
    - identifier: database-credentials
      origin: service
      kind: Secret
      object:
        selector:
          matchLabels:
            # TODO change this once we have the database resource
            syncagent.kcp.io/selector: my-db
          rewrite:
            template:
              template: "{{ .Value }}"
